<?php

namespace AppBundle\Repository;

/**
 * OtherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherRepository extends \Doctrine\ORM\EntityRepository
{
    public function all()
    {
        $qb = $this->createQueryBuilder('o');
        return $qb;

    }

}
