<?php

namespace AppBundle\Repository;

/**
 * StuffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StuffRepository extends \Doctrine\ORM\EntityRepository
{

    public function allStuff()
    {
        $qb = $this->createQueryBuilder('s');

        $qb->leftJoin('s.other', 'o')
            ->addSelect('o');

        return $qb;
    }
}
